[package]
name = "bombay-rs"
description = "A pluggable process runtime over Bombay Behavior."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "bombay"

[[example]]
name = "basic"
path = "../../examples/basic.rs"

[lints]
workspace = true

[dependencies]
behavior = { workspace = true }
bombay-macros = { workspace = true }
bombay-engine = { workspace = true }
bombay-address = { workspace = true }
observe = { workspace = true }
communication = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
timers = { workspace = true }
