//! Transitional closed evidence for locally hosted endpoint types.

use core::hash::Hash;

use behavior::{Behavior, Protocol};

use crate::launch::LocalAddresses;

/// One explicit application composition root.
///
/// Implementations are generated by [`crate::application!`]. The associated
/// topology is pure type evidence; it owns no runtime values.
pub trait Application: Behavior {
    /// Closed topology/capability evidence for this root.
    type Topology: Topology<Root = Self>;
}

/// Closed application evidence separated by capability role.
#[doc(hidden)]
pub trait Topology {
    type Root: Behavior;
    type Namespaces: BuildNamespaces;
}

/// Constructs one Bombay-owned Address-space value for every hosted protocol.
#[doc(hidden)]
pub trait BuildNamespaces: Sized {
    fn build() -> Self;
}

/// Statically selects the one shared Address space for `B`.
#[doc(hidden)]
#[diagnostic::on_unimplemented(
    message = "the application does not host actor protocol `{P}` locally",
    label = "missing local actor protocol",
    note = "add a behavior implementing `{P}` to the `hosted {{ ... }}` list in this root's `application!` declaration"
)]
pub trait Namespace<P>
where
    P: Protocol,
    P::Addr: Hash,
{
    fn namespace(&self) -> LocalAddresses<P>;
}
